import { RegistryRecord } from "../types";

import { ballToBallBounce as ballToBallBounceFormula } from "../../pages/createJSON/formulas/animation/BallToBallBounce";
import { circleCircle } from "../../pages/createJSON/formulas/collision-detection/CircleCollision";
import {
  lineCircle,
  lineLine,
  linePoint,
  LinePolygon,
} from "../../pages/createJSON/formulas/collision-detection/LineCollision";
import { pointCircle } from "../../pages/createJSON/formulas/collision-detection/PointCollision";
import {
  polygonCircle,
  polygonPoint,
  polygonPolygon,
} from "../../pages/createJSON/formulas/collision-detection/PolygonCollision";

export const COLLISION_DETECTION: RegistryRecord[] = [
  {
    slug: "point-to-circle-collision",
    title: "point to circle collision",
    category: "collision detection",
    manifestKey: "PointToCircleCollision",
    formula: pointCircle,
    load: () => import("../../core-animations/PointToCircle"),
    coreExports: ["pointToCircle", "pointCircle"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "point-to-rectangle-collision",
    title: "point to polygon collision",
    category: "collision detection",
    manifestKey: "PointToRectangle",
    formula: polygonPoint,
    load: () => import("../../core-animations/PointToRect"),
    coreExports: ["pointToPolygon", "pointToRect", "polygonPoint"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "rectangle-to-rectangle-collision",
    title: "rectangle to rectangle collision",
    category: "collision detection",
    manifestKey: "RectToRect",
    formula: polygonPolygon,
    load: () => import("../../core-animations/RectToRect"),
    coreExports: ["rectToRect", "rectToPolygon", "polygonPolygon"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "circle-to-rectangle-collision",
    title: "circle to rectangle collision",
    category: "collision detection",
    manifestKey: "CirceToRectCollision",
    formula: polygonCircle,
    load: () => import("../../core-animations/CircleToRect"),
    coreExports: ["circleToRect", "polygonCircle"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "circle-to-circle-collision",
    title: "circle to circle collision",
    category: "collision detection",
    manifestKey: "CircleToCircleCollision",
    formula: circleCircle,
    load: () => import("../../core-animations/CircleToCircle"),
    coreExports: ["circleToCircle", "circleCircle"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "line-to-circle-collision",
    title: "line to circle collision",
    category: "collision detection",
    manifestKey: "LineToCircleCollision",
    formula: lineCircle,
    load: () => import("../../core-animations/LineToCircle"),
    coreExports: ["lineToCircle", "lineCircle"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "line-to-line-collision",
    title: "line to line collision",
    category: "collision detection",
    manifestKey: "LineToLineCollision",
    formula: lineLine,
    load: () => import("../../core-animations/LineToLine"),
    coreExports: ["lineToLine", "lineLine"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "line-to-point-collision",
    title: "line to point collision",
    category: "collision detection",
    manifestKey: "LineToPointCollision",
    formula: linePoint,
    load: () => import("../../core-animations/LineToPoint"),
    coreExports: ["lineToPoint", "linePoint"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "line-to-rectangle-collision",
    title: "line to rectangle collision",
    category: "collision detection",
    manifestKey: "LineToRectangleCollision",
    formula: LinePolygon,
    load: () => import("../../core-animations/LineToRect"),
    coreExports: ["lineToRect", "polygonLine"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "polygon-to-polygon-collision",
    title: "polygon to polygon collision",
    category: "collision detection",
    manifestKey: "PolygonToPolygonCollision",
    formula: polygonPolygon,
    load: () => import("../../core-animations/PolygonToPolygonCollision"),
    coreExports: ["polygonToPolygon", "polygonPolygon"],
    pen: "canonical-vm-tested",
  },
  {
    slug: "circle-field",
    title: "circle field (collision at scale)",
    category: "collision detection",
    manifestKey: "CircleFieldCollision",
    formula: circleCircle,
    load: () => import("../../core-animations/CircleField"),
    coreExports: ["circleToCircle"],
    pen: "canonical",
  },
  {
    // Hidden duplicate of the circle-field bounce (weaker two-ball version).
    // Kept off the sidebar via include:false; CircleField above is the one to show.
    slug: "balls-bouncing-against-each-other",
    title: "balls bouncing against each other",
    category: "collision detection",
    manifestKey: "BallsBouncingAgainstEachOther",
    include: false,
    formula: ballToBallBounceFormula,
    load: () => import("../../core-animations/BallBall"),
    coreExports: ["ballToBallBounce"],
    pen: "canonical-vm-tested",
  },
];
